version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pw_vault
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pwvaultdb
      POSTGRES_USER: pw_user
      POSTGRES_PASSWORD: pw_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
